"""Generate Home Assistant template sensors that re-record rarely-changing helpers.

The InfluxDB integration writes only on a state or attribute change, so a setpoint nobody touches
for months leaves no recent samples and can age out of VictoriaMetrics' retention. A snapshot
sensor copies the helper on a timer and stamps a changing attribute, which forces a write.
"""

from __future__ import annotations

import json
import time

SUPPORTED_DOMAINS = ("input_number", "input_boolean")
ALLOWED_HOURS = (1, 2, 3, 4, 6, 8, 12, 24)
_TEMPLATES = {
    "input_number": "{{{{ states('{eid}') }}}}",
    "input_boolean": "{{{{ 1 if is_state('{eid}', 'on') else 0 }}}}",
}


def select_entities(rows: list[dict], only: str = "stale", stale_days: int = 30,
                    now: float | None = None) -> list[dict]:
    """Helpers worth mirroring: supported, not ignored, not already mirrored (and stale if asked)."""
    now = now or time.time()
    picked = []
    for row in rows:
        domain = row["entity_id"].split(".", 1)[0]
        if domain not in SUPPORTED_DOMAINS or row["vm_status"] in ("ignored", "orphan"):
            continue
        if row.get("mirrored_by") or not row.get("has_state") or row.get("disabled"):
            continue
        if only == "stale":
            seen = row.get("last_value_seen")
            if row["vm_status"] == "ok" and seen and now - seen < stale_days * 86400:
                continue
        picked.append(row)
    return picked


def mirror_yaml(rows: list[dict], hours: int = 6) -> str:
    if hours not in ALLOWED_HOURS:
        raise ValueError(f"hours must be one of {ALLOWED_HOURS}")
    pattern = '"3"' if hours == 24 else f'"/{hours}"'
    lines = [
        "# Snapshot sensors that re-record rarely-changing helpers (generated by the gateway).",
        "# Requires Home Assistant 2024.10 or newer. Add under `template:` in configuration.yaml",
        "# (or a package), run a config check, then reload template entities or restart.",
        "template:",
        "  - triggers:",
        "      - trigger: time_pattern",
        f"        hours: {pattern}",
        '        minutes: "0"',
        "      - trigger: homeassistant",
        "        event: start",
        "    sensor:",
    ]
    if not rows:
        lines[-1] = "    sensor: []  # nothing needs mirroring"
    for row in rows:
        eid = row["entity_id"]
        domain, object_id = eid.split(".", 1)
        if domain not in SUPPORTED_DOMAINS:
            raise ValueError(f"unsupported domain for {eid}")
        # The name is derived from the object id so the new entity is predictably
        # sensor.<object_id>_snapshot, whatever the helper's friendly name is.
        name = object_id.replace("_", " ").title() + " Snapshot"
        lines += [
            f"      # {row.get('friendly_name') or row.get('name') or eid}",
            f"      - name: {json.dumps(name)}",
            f"        unique_id: {json.dumps(object_id + '_snapshot')}",
        ]
        if domain == "input_number":
            if row.get("unit"):
                lines.append(f"        unit_of_measurement: {json.dumps(row['unit'])}")
            lines.append("        state_class: measurement")
        lines += [
            f"        state: {json.dumps(_TEMPLATES[domain].format(eid=eid))}",
            f"        availability: {json.dumps('{{ states(' + repr(eid) + ') not in [' + repr('unknown') + ', ' + repr('unavailable') + '] }}')}",
            "        attributes:",
            f"          source_entity: {json.dumps(eid)}",
            '          recorded_at: "{{ now().isoformat() }}"',
        ]
    return "\n".join(lines) + "\n"
